### ISSUE TITLE
Add Solana compatibility layer

### ISSUE THREAD

**Issue by conr2d** [NoirHQ/noir#94]
## Description

Add Solana compatibility layer including RPC & execution environment emulation

## TODO

- [x] Port `solana_rbpf` to work in no_std
- [x] Implement Solana execution environment emulation
  - [x] `solana-program-runtime` (solana/program-runtime)
  - [x] `solana-programs` (solana/programs)
  - [x] `solana-program` (solana/sdk/program)
  - [x] `solana-sdk` (solana/sdk)
- [x] Implement `pallet-solana` (#109)
- [x] Implement Solana RPC emulation (#115)
